services:
  postgres:
    image: postgres:16.3
    ports:
      - 5442:5432
    expose:
      - 5442
    environment:
      - POSTGRES_USER=felipe
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=personalfinance
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: